//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Quiz_Vendly_2301858345
{
    using System;
    using System.Collections.Generic;
    
    public partial class OurNote
    {
        public int NoteID { get; set; }
        public string Title { get; set; }
        public int Writer { get; set; }
        public string Content { get; set; }
        public string Code { get; set; }
    }
}
